-- Schema inicial do ImobGest, alinhado ao que as telas gravam.
-- Não inclui dados pessoais nem objetos internos do Supabase.

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  nome text,
  email text,
  role text not null default 'admin',
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_role_check check (role = 'admin')
);

create unique index profiles_nome_key
  on public.profiles (nome)
  where nome is not null;

create table public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  documento text,
  telefone text not null default '',
  email text,
  cpf text,
  rg text,
  created_at timestamptz default now()
);

create table public.imoveis (
  id bigint generated by default as identity primary key,
  codigo text,
  tipo text not null default 'Casa',
  finalidade text not null default 'Aluguel',
  cidade text,
  bairro text,
  endereco text,
  quartos integer,
  banheiros integer,
  vagas integer,
  valor numeric(14, 2),
  status text not null default 'disponivel',
  descricao text,
  created_at timestamptz default now(),
  cep text,
  estado text,
  numero text,
  complemento text,
  observacoes text,
  titulo text,
  constraint imoveis_status_check check (
    status = any (array['disponivel', 'alugado', 'manutencao'])
  )
);

create table public.informacoes_adicionais_imoveis (
  id bigint generated by default as identity primary key,
  imovel_id bigint not null references public.imoveis (id) on delete cascade,
  nome_proprietario text,
  codigo_cliente_elektro text,
  codigo_medidor_elektro text,
  codigo_cliente_sabesp_rgi text,
  codigo_medidor_sabesp text,
  codigo_iptu text,
  created_at timestamptz default now()
);

create table public.contratos (
  id bigint generated by default as identity primary key,
  numero text not null,
  imovel text not null,
  cliente text not null,
  tipo text not null,
  inicio date,
  termino date,
  valor numeric(14, 2) not null,
  status text not null default 'ativo',
  observacoes text,
  created_at timestamptz default now(),
  periodicidade text not null default 'Mensal',
  quantidade_dias integer,
  cliente_id bigint references public.clientes (id) on update cascade on delete restrict,
  imovel_id bigint references public.imoveis (id) on update cascade on delete restrict,
  data_inicio date,
  data_fim date,
  valor_aluguel numeric(12, 2) default 0,
  dia_vencimento integer default 10,
  valor_caucao numeric(12, 2) default 0,
  updated_at timestamptz default now(),
  constraint contratos_status_check check (
    status = any (array['ativo', 'encerrado', 'vencido', 'cancelado'])
  ),
  constraint contratos_periodicidade_check check (
    periodicidade = any (array['Mensal', 'Anual', 'Diária', 'Única'])
  ),
  constraint contratos_quantidade_dias_check check (
    quantidade_dias is null or quantidade_dias > 0
  )
);

create table public.recebimentos (
  id bigint generated by default as identity primary key,
  contrato_id bigint references public.contratos (id) on delete set null,
  cliente_id bigint references public.clientes (id) on delete set null,
  categoria text not null default 'Locação',
  valor numeric(14, 2) not null default 0,
  data_recebimento date,
  data_pagamento date,
  forma_pagamento text,
  status text not null default 'Pendente',
  observacoes text,
  created_at timestamptz default now(),
  tipo_recebimento text default 'Aluguel mensal',
  imovel_id bigint,
  competencia date,
  parcela integer,
  total_parcelas integer,
  data_vencimento date,
  quantidade numeric(12, 2),
  valor_unitario numeric(12, 2),
  desconto numeric(12, 2) default 0,
  intervalo_parcelas integer default 1,
  primeira_data_vencimento date,
  descricao text,
  updated_at timestamptz default now(),
  numero_contrato text,
  constraint recebimentos_status_check check (
    status = any (array['Pendente', 'Recebido', 'Pago'])
  ),
  constraint recebimentos_valor_check check (valor >= 0)
);

create table public.despesas (
  id bigint generated by default as identity primary key,
  categoria text not null,
  descricao text not null,
  valor numeric(14, 2) not null default 0,
  data_despesa date not null default current_date,
  forma_pagamento text,
  status text not null default 'Pago',
  observacoes text,
  created_at timestamptz default now(),
  "observações" text,
  constraint despesas_status_check check (
    status = any (array['Pago', 'Pendente', 'Cancelado'])
  ),
  constraint despesas_valor_check check (valor >= 0)
);

create index idx_clientes_nome on public.clientes (nome);
create index idx_imoveis_status on public.imoveis (status);
create index idx_contratos_cliente_id on public.contratos (cliente_id);
create index idx_contratos_imovel_id on public.contratos (imovel_id);
create index idx_contratos_status on public.contratos (status);
create index idx_recebimentos_cliente_id on public.recebimentos (cliente_id);
create index idx_recebimentos_contrato_id on public.recebimentos (contrato_id);
create index idx_recebimentos_vencimento on public.recebimentos (data_vencimento);
create index idx_despesas_data on public.despesas (data_despesa);

-- A tela de contratos grava o id numérico nas colunas texto cliente e imovel.
create or replace function public.sync_contrato_refs()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.cliente ~ '^[0-9]+$' then
    new.cliente_id := new.cliente::bigint;
  end if;

  if new.imovel ~ '^[0-9]+$' then
    new.imovel_id := new.imovel::bigint;
  end if;

  return new;
end;
$$;

revoke all on function public.sync_contrato_refs() from public;
revoke all on function public.sync_contrato_refs() from anon, authenticated;

create trigger contratos_sync_refs
before insert or update on public.contratos
for each row
execute function public.sync_contrato_refs();

alter table public.profiles enable row level security;
alter table public.clientes enable row level security;
alter table public.imoveis enable row level security;
alter table public.informacoes_adicionais_imoveis enable row level security;
alter table public.contratos enable row level security;
alter table public.recebimentos enable row level security;
alter table public.despesas enable row level security;

grant usage on schema public to anon, authenticated;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.clientes from anon, authenticated;
revoke all on table public.imoveis from anon, authenticated;
revoke all on table public.informacoes_adicionais_imoveis from anon, authenticated;
revoke all on table public.contratos from anon, authenticated;
revoke all on table public.recebimentos from anon, authenticated;
revoke all on table public.despesas from anon, authenticated;

grant select on table public.profiles to anon, authenticated;
grant select, insert, update, delete on table public.clientes to authenticated;
grant select, insert, update, delete on table public.imoveis to authenticated;
grant select, insert, update, delete on table public.informacoes_adicionais_imoveis to authenticated;
grant select, insert, update, delete on table public.contratos to authenticated;
grant select, insert, update, delete on table public.recebimentos to authenticated;
grant select, insert, update, delete on table public.despesas to authenticated;

grant usage, select on all sequences in schema public to authenticated;

create policy "login le profiles"
on public.profiles
for select
to anon, authenticated
using (ativo = true);

create policy "autenticado gerencia clientes"
on public.clientes
for all
to authenticated
using (true)
with check (true);

create policy "autenticado gerencia imoveis"
on public.imoveis
for all
to authenticated
using (true)
with check (true);

create policy "autenticado gerencia informacoes adicionais"
on public.informacoes_adicionais_imoveis
for all
to authenticated
using (true)
with check (true);

create policy "autenticado gerencia contratos"
on public.contratos
for all
to authenticated
using (true)
with check (true);

create policy "autenticado gerencia recebimentos"
on public.recebimentos
for all
to authenticated
using (true)
with check (true);

create policy "autenticado gerencia despesas"
on public.despesas
for all
to authenticated
using (true)
with check (true);
